spring.datasource.url=jdbc:mysql://2.2.2.92:3306/bodega_saas?sslMode=REQUIRED&serverTimezone=UTC
spring.datasource.username=bodega_app
spring.datasource.password=TuPasswordSeguro123
# O si usas el usuario bodega_app:
# spring.datasource.username=bodega_app
# spring.datasource.password=TuPasswordSeguro123
